---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:latest
    steps:
      - checkout
      - run: nimble --accept build 
  danger:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn exec danger ci --id "PR" --file "PR-Dangerfile.js"
      - run: yarn exec danger ci --id "nim" --file "Nim-Dangerfile.js"
      - run: yarn exec danger ci --id "site" --file "Site-Dangerfile.js"
workflows:
  version: 2
  primary:
    jobs:
      - build
      - danger
