---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: nimble build --accept
  test:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: nimble build test --accept
      - store_test_results:
          path: report/
      - store_artifacts:
          path: report/
  danger:
    docker:
      - image: library/node:8-alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn exec danger ci

workflows:
  version: 2
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
