---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: apk add pcre
      - run: nimble build --accept
  test:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: apk add pcre
      - run: nimble build --accept
      - run: nimble test
      - store_test_results:
          path: report/
      - store_artifacts:
          path: report/
  danger:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn install
      - run: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD/artifacts | grep -o 'https://[^"]*' > artifacts.txt
      - run: <artifacts.txt xargs -P4 -I % curl %
      - run: yarn danger ci
workflows:
  version: 2
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
