---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: nimble build -y
  danger:
    docker:
      - image: library/node:8-alpine
    environment:
      - DANGER_GITHUB_API_TOKEN
    steps:
      - checkout
      - run: yarn install
      - run: yarn exec danger ci

workflows:
  version: 2
  build_and_danger:
    jobs:
      - build
      - danger
