---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: nimble build --accept
  test:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: nimble -y test
      - store_test_results:
          path: junit.xml
  danger:
    docker:
      - image: library/node:8-alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn exec danger ci

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
