---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: apk add pcre
      - run: nimble build --accept
  test:
    docker:
      - image: nimlang/nim:0.18.0-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add openssl
      - run: apk add pcre
      - run: nimble build --accept
      - run: nimble test
      - store_test_results:
          path: report/
      - store_artifacts:
          path: report/
  danger:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn danger ci
      - run: ls -lsa
workflows:
  version: 2
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
