---
version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim:latest
    steps:
      - checkout
      - run: nimble build
  danger:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
workflows:
  version: 2
  primary:
    jobs:
      - build
      - danger
